import type {Metadata} from "next";
import localFont from "next/font/local";

import "./globals.css";
import React from "react";
import {cookies} from "next/headers";
import {Header} from "@/_components/common/header";
import {Footer} from "@/_components/common/footer";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const yekanBakh = localFont({
    src: "./fonts/YekanBakh.ttf",
    display: "swap",
    variable: "--yekan-font",
    fallback: ["Tahoma", "Arial", "sans-serif"],
});

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const theme = cookieStore.get("theme")?.value || "dark";


    return (
        <html
            lang = "fa"
            dir = "rtl"
            className = {`${yekanBakh.className} h-full `}
            data-theme = {theme}
        >
            <head >
                <link rel = "stylesheet" href = "/lib/web/css/fontawesome.css" />
                <link rel="stylesheet" href="/lib/web/css/solid.css" />
                <link rel="stylesheet" href="/lib/web/css/regular.css" />
                <link rel="stylesheet" href="/lib/web/css/light.css" />

                <link rel="stylesheet" href="/lib/web/css/duotone.css" />
                <link rel="stylesheet" href="/lib/web/css/duotone-light.css" />

                <link rel="stylesheet" href="/lib/web/css/brands.css" />

            </head >
            <body className="leading-6 text-dark fill-gray100 relative">
                <Header />

                {children}
                <Footer />

            </body >
        </html >
    );
}
